version: '2'
services:

  app:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./front:/usr/src/app:cached
    stdin_open: true
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
    - CHOKIDAR_INTERVAL=1000
    ports:
    - 8080:8080