version: '3'
services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./front:/usr/src/app:cached
    stdin_open: true
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
    - CHOKIDAR_INTERVAL=1000
    ports:
    - 8080:8080

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    working_dir: /app/
    volumes:
    - ./back:/app/
    environment:
    - FLASK_APP=app.py
    - HOST=0.0.0.0
    - FLASK_DEBUG=1
    ports:
    - 5000:5000
    command: flask run --host=0.0.0.0 --port 5000
